In [31]:
%matplotlib inline
import matplotlib.pyplot as plt

import pandas as pd

In [32]:
China_Confirmer_group_df = pd.read_csv('../data/Confirmer/China_group_df.csv')
Asia_Confirmer_group_df = pd.read_csv('../data/Confirmer/Asia_group_df.csv')
Europe_Confirmer_group_df = pd.read_csv('../data/Confirmer/Europe_group_df.csv')
America_Confirmer_group_df = pd.read_csv('../data/Confirmer/America_group_df.csv')
Africa_Confirmer_group_df = pd.read_csv('../data/Confirmer/Africa_group_df.csv')
Oceania_Confirmer_group_df = pd.read_csv('../data/Confirmer/Oceania_group_df.csv')

In [33]:
China_Airport_group_df = pd.read_csv('../data/Airport/China_group_df.csv')
Asia_Airport_group_df = pd.read_csv('../data/Airport/Asia_group_df.csv')
Europe_Airport_group_df = pd.read_csv('../data/Airport/Europe_group_df.csv')
America_Airport_group_df = pd.read_csv('../data/Airport/America_group_df.csv')
Africa_Airport_group_df = pd.read_csv('../data/Airport/Africa_group_df.csv')
Oceania_Airport_group_df = pd.read_csv('../data/Airport/Oceania_group_df.csv')

In [34]:
China_Ship_group_df = pd.read_csv('../data/Ship/China_group_df.csv')
Asia_Ship_group_df = pd.read_csv('../data/Ship/Asia_group_df.csv')
Europe_Ship_group_df = pd.read_csv('../data/Ship/Europe_group_df.csv')
America_Ship_group_df = pd.read_csv('../data/Ship/America_group_df.csv')
Africa_Ship_group_df = pd.read_csv('../data/Ship/Africa_group_df.csv')
Oceania_Ship_group_df = pd.read_csv('../data/Ship/Oceania_group_df.csv')

In [35]:
China_News_group_df = pd.read_csv('../data/News/China_group_df.csv')
Asia_News_group_df = pd.read_csv('../data/News/Asia_group_df.csv')
Europe_News_group_df = pd.read_csv('../data/News/Europe_group_df.csv')
America_News_group_df = pd.read_csv('../data/News/America_group_df.csv')
Africa_News_group_df = pd.read_csv('../data/News/Africa_group_df.csv')
Oceania_News_group_df = pd.read_csv('../data/News/Oceania_group_df.csv')

In [36]:
China_Entry_group_df = pd.read_csv('../data/Entry/China_group_df.csv')
Asia_Entry_group_df = pd.read_csv('../data/Entry/Asia_group_df.csv')
Europe_Entry_group_df = pd.read_csv('../data/Entry/Europe_group_df.csv')
America_Entry_group_df = pd.read_csv('../data/Entry/America_group_df.csv')
Africa_Entry_group_df = pd.read_csv('../data/Entry/Africa_group_df.csv')
Oceania_Entry_group_df = pd.read_csv('../data/Entry/Oceania_group_df.csv')

In [37]:
China_Confirmer_group_df.set_index('Date', inplace=True)
Asia_Confirmer_group_df.set_index('Date', inplace=True)
Europe_Confirmer_group_df.set_index('Date', inplace=True)
America_Confirmer_group_df.set_index('Date', inplace=True)
Africa_Confirmer_group_df.set_index('Date', inplace=True)
Oceania_Confirmer_group_df.set_index('Date', inplace=True)

In [38]:
China_Airport_group_df.set_index('Date', inplace=True)
Asia_Airport_group_df.set_index('Date', inplace=True)
Europe_Airport_group_df.set_index('Date', inplace=True)
America_Airport_group_df.set_index('Date', inplace=True)
Africa_Airport_group_df.set_index('Date', inplace=True)
Oceania_Airport_group_df.set_index('Date', inplace=True)

In [39]:
China_Ship_group_df.set_index('Date', inplace=True)
Asia_Ship_group_df.set_index('Date', inplace=True)
Europe_Ship_group_df.set_index('Date', inplace=True)
America_Ship_group_df.set_index('Date', inplace=True)
Africa_Ship_group_df.set_index('Date', inplace=True)
Oceania_Ship_group_df.set_index('Date', inplace=True)

In [40]:
China_News_group_df.set_index('Date', inplace=True)
Asia_News_group_df.set_index('Date', inplace=True)
Europe_News_group_df.set_index('Date', inplace=True)
America_News_group_df.set_index('Date', inplace=True)
Africa_News_group_df.set_index('Date', inplace=True)
Oceania_News_group_df.set_index('Date', inplace=True)

In [41]:
China_Entry_group_df.set_index('Date', inplace=True)
Asia_Entry_group_df.set_index('Date', inplace=True)
Europe_Entry_group_df.set_index('Date', inplace=True)
America_Entry_group_df.set_index('Date', inplace=True)
Africa_Entry_group_df.set_index('Date', inplace=True)
Oceania_Entry_group_df.set_index('Date', inplace=True)

In [42]:
China_concat = pd.concat([China_Confirmer_group_df, China_Airport_group_df, China_Ship_group_df, China_News_group_df, China_Entry_group_df], axis=1)
Asia_concat = pd.concat([Asia_Confirmer_group_df, Asia_Airport_group_df, Asia_Ship_group_df, Asia_News_group_df, Asia_Entry_group_df], axis=1)
Europe_concat = pd.concat([Europe_Confirmer_group_df, Europe_Airport_group_df, Europe_Ship_group_df, Europe_News_group_df, Europe_Entry_group_df], axis=1)
America_concat = pd.concat([America_Confirmer_group_df, America_Airport_group_df, America_Ship_group_df, America_News_group_df, America_Entry_group_df], axis=1)
Africa_concat = pd.concat([Africa_Confirmer_group_df, Africa_Airport_group_df, Africa_Ship_group_df, Africa_News_group_df, Africa_Entry_group_df], axis=1)
Oceania_concat = pd.concat([Oceania_Confirmer_group_df, Oceania_Airport_group_df, Oceania_Ship_group_df, Oceania_News_group_df, Oceania_Entry_group_df], axis=1)

In [43]:
China_concat.fillna(0, inplace=True)
Asia_concat.fillna(0, inplace=True)
Europe_concat.fillna(0, inplace=True)
America_concat.fillna(0, inplace=True)
Africa_concat.fillna(0, inplace=True)
Oceania_concat.fillna(0, inplace=True)

In [44]:
China_concat

,Daily_confirmed,Daily_deaths,Total_confirmed,Flight_departure,Flight_arrivals,Flight_total,Passenger_departure,Passenger_arrivals,Passenger_total,Freight_departure,...,Ship_year,Ship_count,Ship_crew(korea),Ship_crew(foreign),Ship_passenger,News_Daily_Total,News_Sum,News_Negative,News_Positive,China
Date,,,,,,,,,,,,,,,,,,,,,
20191201.0,0.0,0.0,0.0,174.0,176.0,350.0,25424.0,25769.0,51193.0,874.0,...,258432.0,1488.0,286.0,2254.0,1206.0,159.0,3.0,2.0,1.0,0.0
20191202.0,0.0,0.0,0.0,165.0,168.0,333.0,23864.0,22818.0,46682.0,614.0,...,278622.0,3624.0,316.0,2786.0,5700.0,339.0,1.0,1.0,0.0,0.0
20191203.0,0.0,0.0,0.0,171.0,173.0,344.0,21293.0,19728.0,41021.0,833.0,...,335154.0,3824.0,374.0,3134.0,5424.0,376.0,10.0,10.0,0.0,0.0
20191204.0,0.0,0.0,0.0,179.0,167.0,346.0,22142.0,18476.0,40618.0,950.0,...,278622.0,3458.0,228.0,2720.0,5916.0,440.0,13.0,11.0,2.0,0.0
20191205.0,0.0,0.0,0.0,172.0,176.0,348.0,21393.0,22290.0,43683.0,883.0,...,270546.0,3706.0,334.0,2586.0,5672.0,433.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20200502.0,3.0,0.0,83959.0,34.0,19.0,53.0,124.0,0.0,124.0,237.0,...,113120.0,469.0,119.0,989.0,2.0,805.0,98.0,85.0,13.0,0.0
20200503.0,2.0,0.0,83961.0,38.0,22.0,60.0,376.0,288.0,664.0,193.0,...,107060.0,278.0,96.0,903.0,0.0,890.0,80.0,61.0,19.0,0.0
20200504.0,3.0,0.0,83964.0,33.0,23.0,56.0,351.0,270.0,621.0,157.0,...,109080.0,460.0,103.0,917.0,0.0,1418.0,100.0,80.0,20.0,0.0
20200505.0,2.0,0.0,83966.0,37.0,25.0,62.0,0.0,0.0,0.0,396.0,...,109080.0,672.0,89.0,1036.0,0.0,881.0,97.0,85.0,12.0,0.0
20200506.0,2.0,0.0,83968.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
China_concat.to_csv('../data/Concat/China_concat.csv')
Asia_concat.to_csv('../data/Concat/Asia_concat.csv')
Europe_concat.to_csv('../data/Concat/Europe_concat.csv')
America_concat.to_csv('../data/Concat/America_concat.csv')
Africa_concat.to_csv('../data/Concat/Africa_concat.csv')
Oceania_concat.to_csv('../data/Concat/Oceania_concat.csv')