In [1]:
import pandas as pd
import os.path, glob

In [2]:
column = ['항명', '호출부호', '선명', '입항횟수', '입항횟수.1', '구분', '외내', '입출', '총톤수', '국제톤수',
       '징수톤수', '입항일시', '출항일시', 'CIO수속일자', '수리일시', '항해구분', 'MRN 번호', '국적',
       '국적.1', '계선장소', '계선장소.1', '계선장소.2', '차항지', '전출항지', '선박용도', '승무원1',
       '승무원2', '승객', '예선', '도선', '부선호출부호1', '부선호출부호2']

In [3]:
df = pd.DataFrame(columns=column)

In [4]:
ship_path_list = glob.glob( '../data/선박/*' )

for file in ship_path_list : 
    
    filename = os.path.basename( file )
    print(filename)
            
    tmp_df = pd.read_excel(file, header=12)
    tmp_df.columns = column
    df = pd.concat([df,tmp_df])
            
df.reset_index(inplace=True)
df.drop(df.columns[0] , axis=1, inplace=True)
df.to_csv('../data/입항.csv', index=False)

내항입항 201912 - 1.xlsx
내항입항 201912 - 2.xlsx
내항입항 202001 - 1.xlsx
내항입항 202001 - 2.xlsx
내항입항 202002 - 1.xlsx
내항입항 202002 - 2.xlsx
내항입항 202003 - 1.xlsx
내항입항 202003 - 2.xlsx
내항입항 202004 - 1.xlsx
내항입항 202004 - 2.xlsx
내항입항 202005 - 1.xlsx
외항입항 201912 - 1.xlsx
외항입항 201912 - 2.xlsx
외항입항 202001 - 1.xlsx
외항입항 202001 - 2.xlsx
외항입항 202002 - 1.xlsx
외항입항 202002 - 2.xlsx
외항입항 202003 - 1.xlsx
외항입항 202003 - 2.xlsx
외항입항 202004 - 1.xlsx
외항입항 202004 - 2.xlsx
외항입항 202005 - 1.xlsx

In [6]:
df = pd.read_csv('../data/입항.csv')

C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (16,31) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
df.drop( ['호출부호', '선명', '외내', '입출', '국제톤수', '징수톤수', 'CIO수속일자', '수리일시', '항해구분', 'MRN 번호', '국적.1', '계선장소', '계선장소.1', '계선장소.2', 
         '차항지', '부선호출부호1', '부선호출부호2' , '예선', '도선'], axis=1, inplace=True)

In [8]:
df.columns

Index(['항명', '입항횟수', '입항횟수.1', '구분', '총톤수', '입항일시', '출항일시', '국적', '전출항지',
       '선박용도', '승무원1', '승무원2', '승객'],
      dtype='object')

In [9]:
df = df[ df['구분']=='최종' ]

In [10]:
df['전출항지'].unique()

array(['기타항', '동해', '인천', '울산', '제주', '대산', '고현', '광양', '여천항', '완도',
       '옥계항', '군산', '여수', '부산', '포항', '옥포', '목포', '평택.당진', '온산', '당진',
       '묵호', '서귀포', '속초', '진해', '삼천포', '포항신항', '마산', '보령', '삼척', '대불',
       '감천', '장항', '영일만항', '하동화력', '호산항', '통영', '태안', '거문도', '장승포', '서울',
       '경인', '부산 신항', '고흥', 'XIAMEN', 'NEGHISHI/YOKOHAMA', 'SHIMONOSEKI',
       'KOBE', 'NEWCASTLE', 'NOVOROSSIYSK', 'TAICANG', 'NINGBO', 'OITA',
       'FUKUYAMA, HIROSHIMA', 'SON DUONG', 'SHANGHAI', 'QINGDAO PT',
       'NANAO', 'CAOJING', 'VLADIVOSTOK', 'AKITA', 'OCEAN DISTRICT',
       'BAYUQUAN', 'CHANGSHU', 'BALBOA', 'IMABARI', 'ZHENJIANG PT',
       'HAKATA/FUKUOKA', 'TOYAMA', 'NAKHODKA', 'LIANYUNGANG',
       'ZHANGJIAGANG', 'HONG KONG', 'MIZUSHIMA', 'KAOHSIUNG', 'ZHAPU',
       'QINGDAO', 'DANDONG PT', 'KIKUMA', 'SEATTLE', 'SHIDAO PT',
       'SENDAI, MIYAGI', 'TARAKAN, KALIMANTAN', 'YANTAI', 'TAIPEI',
       'NIIGATA', 'BEAUMONT, TX', 'YOKOHAMA', 'OSAKA', 'IYOMISHIMA',
       'WAKAMATSU/KITAKYUSHU', 'YANTIAN PT', 'DAVAO, MINDANAO', 'TIANJIN',
       'JINGTANG(TANGSHAN)', 'BASRA', 'BRISBANE', 'DALIAN', 'TSUKUMI',
       'SAKAI', 'GALLE', 'ZHOUSHAN PT', 'NANTONG PT', 'VUNG TAU',
       'MOJI/KITAKYUSHU', 'BATANGAS/LUZON', 'TOYOHASHI',
       'TANJUNG BARA, KL', 'RICHARDS BAY', 'HIROSHIMA', 'TOKUYAMA',
       'ROBERTS BANK', 'QINHUANGDAO PT', 'HIBIKINADA, FUKUOKA', 'SAKAIDE',
       'WAKAYAMA', 'RAS TANURA', 'TAIXING', 'GLADSTONE', "BUKHTA OL'GA",
       'PHUOC LONG', 'DARWIN', 'KUSHIRO', 'IZUHARA', 'QALHAT',
       'SINGAPORE', 'HITAKATSU', 'CRISTOBAL', 'NANJING', 'WEIHAI',
       'PORT HEDLAND', 'YOKKAICHI', 'JINZHOU PT',
       'PETROPAVLOVSK-KAMCHATSKIY', 'NAOSHIMA', 'CAI LAN', 'SHIMOTSU',
       'HIGASHIHARIMA', 'KINUURA', 'ISHIKARIWAN-SHINKO, HOKKAIDO',
       'WAIGAOQIAO PT', 'LONGKOU PT', 'SHIMIZU', 'HO CHI MINH CITY',
       'VANCOUVER', 'CHANGSHU PT', 'JIANGYIN PT', 'HUANGHUA PT', 'CHOFU',
       'TAICHUNG', 'FUNABASHI', 'RUMOI', 'MATSUYAMA', 'RUGAO PT',
       'KAINAN', 'MURORAN', 'ROXAS/PUERTO PRINCESA', 'AL FUJAYRAH',
       'CHIBA', 'KHOLMSK', 'KUANTAN (TANJONG GELANG)', 'TIMARU',
       'NAGASAKI', 'VOSTOCHNYY PORT', 'CAOFEIDIAN PT', 'LANSHAN PT',
       'ZHAPU PT', 'ZARUBINO', 'VANINO', 'BITUNG, SULAWESI', 'TSURUGA',
       'BARROW ISLAND', 'DONGYING PT', 'NAGOYA, AICHI',
       'KEELUNG (CHILUNG)', 'RIZHAO PT', 'TIANJIN XINGANG PT',
       'BEIHAI PT', 'TOMAKOMAI', 'OAKLAND, CA', 'LONGBEACH', 'WEIFANG PT',
       'KAKOGAWA', 'KUROSAKI', 'HITACHINAKA', 'SLAVYANKA', 'KUDAMATSU',
       'PAPEETE', 'HIGASHI-OGISHIMA', 'PORTLAND, OR', 'HACHINOHE',
       'ZHANJIANG', 'SHEKOU PT', 'KANAZAWA', 'SHANTOU', 'TOKYO', 'RUWAIS',
       'MISUMI, SHIMANE', 'NINGDE', 'IMARI', 'ANYER KIDUL', 'IWAKUNI',
       'DONGGUAN PT', 'DE-KASTRI', 'NANSHA PT', 'UBE', 'LONGYAN PT',
       'SANDIEGO', 'HONOLULU', 'SAMARINDA, KALIMANTAN', 'VAN PHONG',
       'LAIZHOU PT', 'GROOTE EYLANDT', 'TAIZHOU', 'KASHIMAE',
       'LIMAY/BATAAN', 'MITAJIRI', 'CAYO ARCAS TERMINAL', 'RAS LAFFAN',
       'KAWASAKI', 'MANILA SOUTH HARBOUR', 'SAKATA', 'YANTAI PT',
       'BALIKPAPAN', 'WEIFANG', 'JINGJIANG', 'FUJIN', 'OKINAWA, OKINAWA',
       'JIUZHOU PT', 'HOSOSHIMA', 'NINGBO PT', 'YINGKOU PT', 'PORT LOUIS',
       'JIANGYIN', 'MAJURO', 'SHAKHTERSK', 'LAHAD DATU, SABAH', 'ITOZAKI',
       'MANZANILLO', 'SHANGHAI PT', 'CHANGZHOU PT', 'PORT MELLON',
       'YANBU AL-BAHR', 'SAKAIMINATO', 'SABINE', 'UWAJIMA', 'EL SUWEIS (',
       'PRIGORODNOYE', 'YATSUSHIRO', 'BAHIA BLANCA', 'SUSAKI',
       'JINGTANG PT', 'MINA AL AHMADI', 'OTAKE', 'SATSUMASENDAI',
       'SITRAH', 'AMAMAPARE, IJ', 'KIIRE', 'PADANG', 'KOMENOTSU', 'LUMUT',
       'ETAJIMA', 'ARIAKE, TOKYO', 'KASHIMA, IBARAKI', 'MANILA',
       'TABONEO', 'ISHIKARI', 'DA CHAN BAY', 'DA NANG', 'KIMITSU',
       'NORTH PACIFIC OCEAN', 'NAHA, OKINAWA', 'HAKODATE', 'FUZHOU',
       'WAKAMATSU, NAGASAKI', 'HIMEKAWA', 'MUTSURE', 'Qidong Pt',
       'LABUAN, SABAH', 'MAI-LIAO', "YUZHNO-KURIL'SK",
       'TROIS-RIVIERES (THREE RIVERS)', 'PLASTUN', 'OSHIMA, NAGASAKI',
       'XINGANG', 'JAKARTA, JAVA', 'REIHOKU', 'MATSUURA, NAGASAKI',
       'TOYAMASHINKO', 'LOSANGELES', 'JAPAN /OTHER-PORT/', 'PENGLAI',
       'OKHOTSK', 'KARATSU', 'WYNDHAM', 'NANJING PT', 'KANDA, FUKUOKA',
       'YANGZHOU PT', 'TAURANGA', 'PORT WALCOTT', 'SENZAKI', 'TACOMA',
       'PORT SAID', 'KORSAKOV', 'KHOR AL FAKKAN', 'JAPAN ODAIBA',
       'KURE, HIROSHIMA', 'OURA/ARIAKE', 'NIIHAMA', 'YAMAGUCHI',
       'ONAHAMA', 'AN PING', 'TARAWA', 'SHIKAMA', 'FUNAFUTI', 'YANGSHAN',
       'LINGGA, SARAWAK', 'HUANGHUA', 'MATSUSHIMA, NAGASAKI',
       'PORT DALRYMPLE', 'KATAKAMI', 'CALLAO', '부평/인천', 'KASHIMA, SAGA',
       'PORTKELANG', 'PANJIN', 'SAKAISENBOKU', 'HINASE',
       'FUKUYAMA, KAGOSHIMA', 'SAIGO, SHIMANE', 'FREDERICKTOWN', 'HAMADA',
       'PICTON', 'DONGYING', 'KAWANOE', 'MATANE', 'NAOETSU', 'KINGSTON',
       'LAIZHOU', 'NADAHAMA', 'SAI GON PT', 'JINGJIANG PT', 'HUALIEN',
       'TOUYO', 'DAFENG PT', 'KOZMINO PORT', 'NAGOYA, OITA', 'FUZHOU PT',
       'HITACHI', 'YAWATA, FUKUOKA', 'SASEBO', 'NORO, NEW GEORGIA',
       'YIZHENG', 'ZHANGZHOU PT', 'CAPE TOWN', 'SAIPAN', 'CANAL',
       'HONGAI', 'ONOMICHI', 'GO DAU A TERMINAL', 'BOTANY BAY',
       'BINTULU, SARAWAK', 'BLUFF', 'DAS ISLAND', 'HUANGPU PT',
       'ANTOFAGASTA', 'CLATSKANIE', 'ABBOT POINT', 'PHITSANULOK',
       'NOSHIRO', 'ADANG BAY', 'VISAKHAPATNAM', 'DAYAOWAN',
       'CHANGZHOU, JIANGAU', 'HIRO', 'CORPUSCHRISTI', 'ALBANY, NY',
       'GALVESTON', 'KUMAMOTO', 'KAGOSHIMA', 'DAGANG', 'WOODRIVER',
       'PANAMA, CIUDAD DE', 'MAIZURU', 'KALTAG', 'DONGJIANGKOU', 'OREGON',
       'BATAAN, MARIVELES', 'LIRQUEN', 'PHU MY', 'BALOGO/BATANGAS',
       'JEBEL ALI', 'CAIRNS', 'PORT MORESBY', 'ONSLOW', 'LU-HUA SHAN',
       'NECOCHEA', 'INDONESIA /OTHER-POR', 'KRIBI', 'JIAXING',
       'PELABUHAN FUTONG', 'LA LIBERTAD', 'QUANZHOU PT', 'PORTMANATEE',
       'HOUSTON, TX', 'KOKURA', 'TAICANG PT', 'PONTA DA MADEIRA',
       'QINZHOU PT', 'NAKETY', 'ISHINOMAKI', 'PARADIP GARH',
       'ILIGAN, MINDANAO', 'TAKASAGO', 'TANJUNG PELEPAS', 'DAMPIER',
       'MISUMI, KUMAMOTO', 'PANJANG', 'DUTCHHARBOR', 'TAKUMA',
       'LAEM CHABANG', 'JINSHAN', 'MAGADAN', 'OTHERS', 'ICHIHARA', 'SUEZ',
       'BAOSHAN PT', 'KWINANA', 'SHIMABARA', 'BONTANG, KL', 'FUSHIKI',
       'LUWUK', 'KAJIKI', 'GEELONG', 'TAGONOURA', 'TOWNSVILLE',
       'OMAEZAKI', 'GISBORNE', 'TAWAU, SABAH',
       'SHEKOU (CODE CHANGE CN SHK))', 'PORO', 'GRESIK, JAVA',
       'USELESS LOOP', 'KOCHI', 'MATARANI', 'MACKAY', 'RAS AL KHAIR',
       'HULUDAO PT', 'PENGGARANG/TANJ.PENGILEH', 'TUAPSE',
       'GRAYSHARBORCITY', 'GUANGZHOU', 'NAKANOSEKI', 'POSO, SULAWESI',
       'DONG NAI', 'DAFENG', 'POINT LISAS', 'KOROR', 'TANGSHAN',
       'WESTPORT/PORT KLANG', 'SODEGAURA', 'XINHUI PT', 'FREMANTLE',
       'KWAJALEIN', 'NOUMEA', 'COCHIN', 'VIETNAM /OTHER-PORT/',
       'PORT ELIZABETH', 'PENGLAI PT', 'MIIKE, TOKYO', 'TIANJIN PT',
       'KERTEH TERMINAL', 'CULAO', 'HIMEJI', 'ITAGUAI', 'POSYET',
       'ANCHORAGE', 'DUNEDIN', 'SANDAKAN, SABAH', 'ICHIKAWA',
       'TAMASHAIMA', 'SAGANOSEKI', 'SONGXIA PT', 'FANGCHENG PT', 'RODMAN',
       'HAY POINT', 'CHENNAI (EX MADRAS)', 'SHIBUSHI', 'CALAPAN/BATANGAS',
       'AOMORI', 'GAMBA', 'MATSUURA, OITA', 'MINA ABD ALLAH', 'CAM PHA',
       'SUAO', 'PISCO', 'MISHIMA, KAWANOE', 'MINE', 'MUARA PANTAI',
       'KHANOM', 'GERALDTON', 'QIANWAN', 'HAIPHONG', 'TOBATA, FUKUOKA',
       'STEWART', 'HAIKOU', 'TACHIBANA', 'RONGCHENG', 'TAIZHOU PT',
       'MIHARA', 'CHITA', 'COOSBAY', 'LAZARO CARDENAS', 'TEOUDIE', 'OKI',
       'KISHIWADA', 'KUNAK, SABAH', 'WENZHOU PT', 'PORTHUENEME',
       'BANJARMASIN', 'JIAXING PT', 'ZHANJIANG PT',
       'AUSTRALIA /OTHER-POR', 'Bunati', 'SUNGAI RENGIT',
       'DONALDSONVILLE', 'KOH SICHANG', 'XIAOHUDAO', 'SATTAHIP',
       'BINTUNI', 'PORTLAND, IN', 'ZURKU ISLAND', 'NEVELSK', 'NELSON',
       'MIYAKO, IWATE', 'CHENGXI', 'NEDERLAND, CO', 'ONODA',
       'SANFRANCISCO', 'CALETA COLOSO', 'DUMAI, SUMATRA',
       'POHNPEI (EX PONAPE)', 'SENDAISHIOGAMA', 'BEARCREEK',
       'LUSHUN NEW PT', 'SEVERO-KURILSK', 'MARSDEN POINT',
       'BRUNSWICK, GA', 'NAMIKATA', 'SHINMOJI', 'ASTORIA',
       'KIMANIS, SABAH', 'NGHI SON', 'HUIZHOU PT', 'NEWORLEANS',
       'SIAM BANGKOK PORT', 'MIYAZU', 'TARJUN', 'LUANJIAKOU', 'MATSUNAGA',
       'LONGVIEW', 'MAZATLAN', 'KURE, KOCHI', 'CIGADING, JV', 'SHIGEI',
       'BATONROUGE', 'CHARLESTON, SC', 'CHAN MAY PORT', 'MAANSHAN PT',
       'CHINA/MACHONG', 'SAN NICOLAS', 'ISABEL', 'SUNRISEBEACH', 'SIKA',
       'RAYONG', 'SAIKI', 'XIUYU', 'TOKUSHIMA', 'NEW WESTMINSTER',
       'SAN ANTONIO', 'MAGADANSKY, PORT', 'AMAGASAKI', 'MAKURAZAKI',
       'SOVETSKAYA GAVAN', 'MORRO REDONDO', 'FERNDALE, WA', 'XIAMEN PT',
       'DALRYMPLE ISLET', 'MAOMING', 'MALACCA', 'HONIARA, GUADALCANAL IS',
       'KASADO', 'COLLEGEVILLE, MN', 'PLAQUEMINE', 'MUARA BERAU',
       'OFFSHORE FUJAIRAH', 'IWAGI,EHIME', 'TATSUGO', 'MERAK, JAVA',
       'DEVONPORT', 'BASUO', 'USUKI', 'CAI MEP INTERNATIONAL TERMINAL',
       'CAVITE, LUZON', 'WESTERNPORT', 'MEJILLONES',
       'MEXICO /OTHER-PORT/', 'COLOMBO', 'TADOTSU', 'CHENJIAGANG',
       'GUANGZHOU PT', 'NAGAHAMA, EHIME', 'BENICIA', 'MIN-AL-FAHAL',
       'BACON/LEGASPI', 'FREEPORT, TX', 'LAUTOKA', 'PRINCE RUPERT',
       'GULEI', 'ENSENADA', 'HIBI', 'BONNY', 'MIIKE, FUKUOKA',
       'PALEMBANG, SUMATRA', 'VINH', 'DALIAN PT', 'WUHU PT', 'OTHER PORT',
       'BANGKOK', 'EL ISKANDARIYA (ALEXANDRIA)', 'TAKAMATSU',
       'HIROTA, IWATE', 'MIYAZAKI, MIYAZAKI', 'SUVA', 'PORTANGELES',
       'TSUSHIMA, NAGASAKI', 'JUAYMAH TERMINAL', 'PASIR GUDANG, JOHOR',
       'MIRI, SARAWAK', 'TAHARA', 'AIOI', 'PANAMACITY', 'HIKARI',
       'KEMAMAN', 'RICHMOND, CA', 'KOTA KINABALU, SABAH', 'OLYMPIA',
       'NAKAGUSUKU', 'YOKOSUKA', 'HIDAKA', 'SUBIC BAY', 'PORT TEWFIK',
       'AD DAMMAM', 'FUQING', 'LAKECHARLES', 'TSURUMI, KANAGAWA',
       'HO CHI MINH, VICT', 'HIKOSHIMA', 'HIZENOHSHIMA', 'BURNIE',
       'GRAMERCY', 'MATSUURA, KAGOSHIMA', 'SERIA', 'HABU, HIROSHIMA',
       'SURABAYA', 'FUKUOKA, FUKUOKA', 'GEISMAR', 'CAPE FLATTERY',
       'WEIHAI PT', 'VUDA', 'BAN MAP TA PHUT', 'MALAYSIA /OTHER-PORT',
       'VALDEZ', 'DANDONG', 'HUMEN PT', 'GENERAL SANTOS', 'NUMAZU',
       'NIPAH', 'PITTSBURG, CA', 'KASHIWAZAKI', 'ASHBURTON', 'GUAM',
       'QUI NHON', 'JURONG', 'YANGPU PT', 'SALVADOR', 'KITANADA',
       'NIIGATAHIGASHI', '남항', '목포 북항', 'FUKUI', 'NEW MANGALORE',
       'CAGAYAN DE ORO, MINDANAO', 'SHARK BAY', 'PUTIAN', 'CEBU',
       'QUANZHOU', 'SHANTOU PT', 'BOGO/CAGAYAN DE ORO', 'CAMRANH',
       'CO-OPERATION ZONE A (AU,ID)', 'SALDANHA BAY', 'MAMONAL',
       'WESTHAMPTONBEACH', 'BERGEN', 'TAKAHAMA/AMAKUSA', 'ZHUHAI PT',
       'JAMBI, SUMATRA', 'EBEYE', 'NEPOUI', 'SHENZHEN',
       'NANYO, YAMAGUCHI', 'KIMBE', 'SHIMOJISHIMA, OKINAWA',
       'TANJUNG LANGSAT', 'ACAJUTLA', 'SATUI', 'SANBAIMEN',
       'ECUADOR /OTHER-PORT/', 'BARROW ISLAND, WA', 'TONDA',
       'TONGLING PT', 'HIAGARI/KITAKIUSHU', 'PORTO ALEGRE', 'TUTICORIN',
       'BING BONG', 'SALALAH', 'ONISHI', 'PORT KEMBLA', 'NANAIMO',
       'Calaca', 'NEDERLAND, TX', 'DEFENG', 'TANIYAMA', 'JUBAIL',
       'HOUSTON, PA', 'PORT MOODY', 'PUERTO QUETZAL', 'GOVE',
       'LEGASPI APT, LUZON', 'ALBANY', 'BANGGAI', 'CAPE CUVIER', 'JOETSU',
       'NAPIER', 'HAIYANG', 'PUNTA LOBITOS', 'KUMAI', 'SAKURAJIMA',
       'HIROHATA', 'KUALA ENOK', 'HIRARA', 'PHILADELPHIA', 'YUSU',
       'OTHER', 'MAKASSAR', 'USHIBUKA', 'PONTIANAK, KALIMANTAN',
       'VICTORIA', 'PAMPLONA/APARRI', 'HAKATASHIMA',
       'PIPAVAV (VICTOR) PORT', 'FUTAJIMA, FUKUOKA', 'WENZHOU',
       'FUKUSHIMA, MIYAZAKI', 'CONSTANTA', 'UMM QASR', 'CILEGON',
       'PHILIPPINES /OTHER-P', 'DUNG QUAT', 'MASCOT', 'SANTOS',
       'JASAAN/CAGAYAN DE ORO', 'HAIMEN', 'HUASCO', 'NAGASU, KUMAMOTO',
       'OHGISHIMA', 'LUOYANG', 'GO DAU B TERMINAL', 'YAWATAHAMA',
       'MOURILYAN', 'BUNBURY', 'WELLINGTON', 'ELLISVILLE, MS', 'MARSHALL',
       'KANDLA', 'KOSRAE (EX KUSAIE)', 'ZHENHAI PT', 'SRIRACHA',
       'ROSARITO TERMINAL', 'BENOA, BALI', 'CAP LOPEZ', 'YANGJIANG PT',
       'NOBEOKA', 'SYDNEY', 'ALBUERA', 'COLON', 'MINAMATA', 'TSUNEISHI',
       'JINGZHOU PT', 'SUNGAI PAKNING, SUMATRA', 'ISHIGAKI', 'IQUIQUE',
       'OHIGAWA', '칼리오랑', 'NANKO', 'ANGRA DOS REIS', 'PORT CHALMERS',
       'CHONGMING', 'AUCKLAND', 'BACOLOD, NEGROS', 'KUWAIT',
       'HUANGPU NEW PORT', 'BRASS', 'TANJONG BIN', 'KYOTO, KYOTO',
       'VIZAGAPATANAM', 'COLUMBUS, MO', 'TANGSHAN PT', 'KOUAOUA',
       'RABAUL', 'MUARA', 'EGYPT /OTHER-PORT/', 'XINSHA',
       'ONOMICHIITOZAKI', 'KINOE', 'KAVKAZ', 'MELBOURNE', 'MAJI SHAN',
       'SANTO DOMINGO', 'KINNAKAGUSUKU', 'GUAYMAS', 'MUMBAI (EX BOMBAY)',
       'CUA VIET PORT', 'TANJUNG PRIOK', 'NEWPORT, OR', 'HALDIA',
       'NAKATSU', 'TAMANO', 'KHOR AL ZUBAIR', 'MITSUKOSHIMA', 'YAMAGAWA',
       'KAWAJIRI, HIROSHIMA', 'TENERIFE', 'TAIWAN PRO.OF CHINA',
       'TAGOLOAN MIS.', 'BENGKULU, SUMATRA', 'LA PAZ',
       'LUGAIT/CAGAYAN DE ORO', 'KONE', 'SOYO', 'DUQM', 'OTARU',
       'PEARLHARBOR', 'CEYHAN', 'THA SALA', 'LYTTELTON', 'CIENAGA',
       'PUNTA MORALES', 'IWANAI', 'BROOME', 'GAMAGORI', 'COLON FREE ZONE',
       'HAMBANTOTA', 'BATAM ISLAND', 'AKITSU', 'SAIJO', 'OBI ISLAND',
       'NETHERLANDS ANTILLES', 'YAP', 'BENETE', 'JEDDAH', 'NAURU ISLAND',
       'SOHAR', 'ZHONGSHAN PT', 'MACUN', 'KANOKAWA', 'SAN JOSE',
       'PORT ALMA', 'DAMMAN', 'LOBITOS', 'CORINTO', 'YANGKOU', 'KISARAZU',
       'PORT VILA', 'MALABO', 'MAB TAPUD', 'TABANGOA', 'SANTA MARTA',
       'SHENHU', 'KITIMAT', 'CHERRYPOINT', 'MADANG', 'HOUND POINT',
       'JIEYANG', 'OROBAY', 'KASAOKA', 'KOLKATA (EX CALCUTTA)', 'HANNAN',
       'INNOSHIMA', 'PUERTO COLOMBIA', 'KITAKYUSHU', 'LONG YAN'],
      dtype=object)

In [11]:
korea_ship = [ '기타항', '동해', '인천', '울산', '제주', '대산', '고현', '광양', '여천항', '완도',
       '옥계항', '군산', '여수', '부산', '포항', '옥포', '목포', '평택.당진', '온산', '당진',
       '묵호', '서귀포', '속초', '진해', '삼천포', '포항신항', '마산', '보령', '삼척', '대불',
       '감천', '장항', '영일만항', '하동화력', '호산항', '통영', '태안', '거문도', '장승포', '서울',
       '경인', '부산 신항', '남항', '목포 북항', '칼리오랑' ]

In [12]:
mask = df['전출항지'].apply( lambda x : False if x in korea_ship else True )

In [13]:
df = df[ mask ]
df

,항명,입항횟수,입항횟수.1,구분,총톤수,입항일시,출항일시,국적,전출항지,선박용도,승무원1,승무원2,승객
41147,부산,2020,1,최종,749,2020-04-28 03:00,2020-04-28 08:20,KR,고흥,일반화물선,3.0,5.0,0.0
42978,인천,2019,9,최종,"17,225",2019-12-01 00:00,2019-12-01 07:05,HK,XIAMEN,풀컨테이너선,NaN,20.0,NaN
42979,여수,2019,3,최종,"4,060",2019-12-01 00:05,2019-12-02 20:40,KR,NEGHISHI/YOKOHAMA,석유제품 운반선,5.0,12.0,NaN
42980,부산,2019,130,최종,465,2019-12-01 00:10,2019-12-02 20:30,KR,SHIMONOSEKI,냉동.냉장선,4.0,7.0,NaN
42982,부산,2019,44,최종,"5,534",2019-12-01 00:20,2019-12-02 15:25,KR,KOBE,일반화물선,5.0,10.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79614,군산,2020,4,최종,"1,937",2020-05-05 22:10,NaN,TG,WEIFANG,일반화물선,NaN,10.0,NaN
79615,대산,2020,2,최종,"42,411",2020-05-05 22:12,2020-05-08 06:00,PK,SINGAPORE,석유제품 운반선,NaN,24.0,NaN
79617,부산,2020,1,최종,"60,178",2020-05-05 22:30,2020-05-07 09:00,LR,YINGKOU PT,원유운반선,NaN,21.0,NaN
79620,부산,2020,9,최종,"12,545",2020-05-05 23:00,2020-05-06 08:12,KR,SHEKOU PT,풀컨테이너선,6.0,14.0,NaN
79621,군산,2020,17,최종,"9,940",2020-05-05 23:42,2020-05-06 14:05,CY,QINGDAO,풀컨테이너선,NaN,18.0,NaN

In [14]:
df.drop([ '구분', '항명'], axis = 1, inplace=True)

In [15]:
df.fillna(0, inplace=True)

In [16]:
df

,입항횟수,입항횟수.1,총톤수,입항일시,출항일시,국적,전출항지,선박용도,승무원1,승무원2,승객
41147,2020,1,749,2020-04-28 03:00,2020-04-28 08:20,KR,고흥,일반화물선,3.0,5.0,0.0
42978,2019,9,"17,225",2019-12-01 00:00,2019-12-01 07:05,HK,XIAMEN,풀컨테이너선,0.0,20.0,0.0
42979,2019,3,"4,060",2019-12-01 00:05,2019-12-02 20:40,KR,NEGHISHI/YOKOHAMA,석유제품 운반선,5.0,12.0,0.0
42980,2019,130,465,2019-12-01 00:10,2019-12-02 20:30,KR,SHIMONOSEKI,냉동.냉장선,4.0,7.0,0.0
42982,2019,44,"5,534",2019-12-01 00:20,2019-12-02 15:25,KR,KOBE,일반화물선,5.0,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
79614,2020,4,"1,937",2020-05-05 22:10,0,TG,WEIFANG,일반화물선,0.0,10.0,0.0
79615,2020,2,"42,411",2020-05-05 22:12,2020-05-08 06:00,PK,SINGAPORE,석유제품 운반선,0.0,24.0,0.0
79617,2020,1,"60,178",2020-05-05 22:30,2020-05-07 09:00,LR,YINGKOU PT,원유운반선,0.0,21.0,0.0
79620,2020,9,"12,545",2020-05-05 23:00,2020-05-06 08:12,KR,SHEKOU PT,풀컨테이너선,6.0,14.0,0.0
79621,2020,17,"9,940",2020-05-05 23:42,2020-05-06 14:05,CY,QINGDAO,풀컨테이너선,0.0,18.0,0.0

In [17]:
df.columns = [ 'Ship_year', 'Ship_count', 'Ship_Total_tonnage', 'Ship_arrival', 'Ship_departure', 'Ship_Nation', 'Ship_Prev_port', 
              'Ship_purpose', 'Ship_crew(korea)', 'Ship_crew(foreign)', 'Ship_passenger']

In [18]:
df['Ship_Prev_port'].unique()

array(['고흥', 'XIAMEN', 'NEGHISHI/YOKOHAMA', 'SHIMONOSEKI', 'KOBE',
       'NEWCASTLE', 'NOVOROSSIYSK', 'TAICANG', 'NINGBO', 'OITA',
       'FUKUYAMA, HIROSHIMA', 'SON DUONG', 'SHANGHAI', 'QINGDAO PT',
       'NANAO', 'CAOJING', 'VLADIVOSTOK', 'AKITA', 'OCEAN DISTRICT',
       'BAYUQUAN', 'CHANGSHU', 'BALBOA', 'IMABARI', 'ZHENJIANG PT',
       'HAKATA/FUKUOKA', 'TOYAMA', 'NAKHODKA', 'LIANYUNGANG',
       'ZHANGJIAGANG', 'HONG KONG', 'MIZUSHIMA', 'KAOHSIUNG', 'ZHAPU',
       'QINGDAO', 'DANDONG PT', 'KIKUMA', 'SEATTLE', 'SHIDAO PT',
       'SENDAI, MIYAGI', 'TARAKAN, KALIMANTAN', 'YANTAI', 'TAIPEI',
       'NIIGATA', 'BEAUMONT, TX', 'YOKOHAMA', 'OSAKA', 'IYOMISHIMA',
       'WAKAMATSU/KITAKYUSHU', 'YANTIAN PT', 'DAVAO, MINDANAO', 'TIANJIN',
       'JINGTANG(TANGSHAN)', 'BASRA', 'BRISBANE', 'DALIAN', 'TSUKUMI',
       'SAKAI', 'GALLE', 'ZHOUSHAN PT', 'NANTONG PT', 'VUNG TAU',
       'MOJI/KITAKYUSHU', 'BATANGAS/LUZON', 'TOYOHASHI',
       'TANJUNG BARA, KL', 'RICHARDS BAY', 'HIROSHIMA', 'TOKUYAMA',
       'ROBERTS BANK', 'QINHUANGDAO PT', 'HIBIKINADA, FUKUOKA', 'SAKAIDE',
       'WAKAYAMA', 'RAS TANURA', 'TAIXING', 'GLADSTONE', "BUKHTA OL'GA",
       'PHUOC LONG', 'DARWIN', 'KUSHIRO', 'IZUHARA', 'QALHAT',
       'SINGAPORE', 'HITAKATSU', 'CRISTOBAL', 'NANJING', 'WEIHAI',
       'PORT HEDLAND', 'YOKKAICHI', 'JINZHOU PT',
       'PETROPAVLOVSK-KAMCHATSKIY', 'NAOSHIMA', 'CAI LAN', 'SHIMOTSU',
       'HIGASHIHARIMA', 'KINUURA', 'ISHIKARIWAN-SHINKO, HOKKAIDO',
       'WAIGAOQIAO PT', 'LONGKOU PT', 'SHIMIZU', 'HO CHI MINH CITY',
       'VANCOUVER', 'CHANGSHU PT', 'JIANGYIN PT', 'HUANGHUA PT', 'CHOFU',
       'TAICHUNG', 'FUNABASHI', 'RUMOI', 'MATSUYAMA', 'RUGAO PT',
       'KAINAN', 'MURORAN', 'ROXAS/PUERTO PRINCESA', 'AL FUJAYRAH',
       'CHIBA', 'KHOLMSK', 'KUANTAN (TANJONG GELANG)', 'TIMARU',
       'NAGASAKI', 'VOSTOCHNYY PORT', 'CAOFEIDIAN PT', 'LANSHAN PT',
       'ZHAPU PT', 'ZARUBINO', 'VANINO', 'BITUNG, SULAWESI', 'TSURUGA',
       'BARROW ISLAND', 'DONGYING PT', 'NAGOYA, AICHI',
       'KEELUNG (CHILUNG)', 'RIZHAO PT', 'TIANJIN XINGANG PT',
       'BEIHAI PT', 'TOMAKOMAI', 'OAKLAND, CA', 'LONGBEACH', 'WEIFANG PT',
       'KAKOGAWA', 'KUROSAKI', 'HITACHINAKA', 'SLAVYANKA', 'KUDAMATSU',
       'PAPEETE', 'HIGASHI-OGISHIMA', 'PORTLAND, OR', 'HACHINOHE',
       'ZHANJIANG', 'SHEKOU PT', 'KANAZAWA', 'SHANTOU', 'TOKYO', 'RUWAIS',
       'MISUMI, SHIMANE', 'NINGDE', 'IMARI', 'ANYER KIDUL', 'IWAKUNI',
       'DONGGUAN PT', 'DE-KASTRI', 'NANSHA PT', 'UBE', 'LONGYAN PT',
       'SANDIEGO', 'HONOLULU', 'SAMARINDA, KALIMANTAN', 'VAN PHONG',
       'LAIZHOU PT', 'GROOTE EYLANDT', 'TAIZHOU', 'KASHIMAE',
       'LIMAY/BATAAN', 'MITAJIRI', 'CAYO ARCAS TERMINAL', 'RAS LAFFAN',
       'KAWASAKI', 'MANILA SOUTH HARBOUR', 'SAKATA', 'YANTAI PT',
       'BALIKPAPAN', 'WEIFANG', 'JINGJIANG', 'FUJIN', 'OKINAWA, OKINAWA',
       'JIUZHOU PT', 'HOSOSHIMA', 'NINGBO PT', 'YINGKOU PT', 'PORT LOUIS',
       'JIANGYIN', 'MAJURO', 'SHAKHTERSK', 'LAHAD DATU, SABAH', 'ITOZAKI',
       'MANZANILLO', 'SHANGHAI PT', 'CHANGZHOU PT', 'PORT MELLON',
       'YANBU AL-BAHR', 'SAKAIMINATO', 'SABINE', 'UWAJIMA', 'EL SUWEIS (',
       'PRIGORODNOYE', 'YATSUSHIRO', 'BAHIA BLANCA', 'SUSAKI',
       'JINGTANG PT', 'MINA AL AHMADI', 'OTAKE', 'SATSUMASENDAI',
       'SITRAH', 'AMAMAPARE, IJ', 'KIIRE', 'PADANG', 'KOMENOTSU', 'LUMUT',
       'ETAJIMA', 'ARIAKE, TOKYO', 'KASHIMA, IBARAKI', 'MANILA',
       'TABONEO', 'ISHIKARI', 'DA CHAN BAY', 'DA NANG', 'KIMITSU',
       'NORTH PACIFIC OCEAN', 'NAHA, OKINAWA', 'HAKODATE', 'FUZHOU',
       'WAKAMATSU, NAGASAKI', 'HIMEKAWA', 'MUTSURE', 'Qidong Pt',
       'LABUAN, SABAH', 'MAI-LIAO', "YUZHNO-KURIL'SK",
       'TROIS-RIVIERES (THREE RIVERS)', 'PLASTUN', 'OSHIMA, NAGASAKI',
       'XINGANG', 'JAKARTA, JAVA', 'REIHOKU', 'MATSUURA, NAGASAKI',
       'TOYAMASHINKO', 'LOSANGELES', 'JAPAN /OTHER-PORT/', 'PENGLAI',
       'OKHOTSK', 'KARATSU', 'WYNDHAM', 'NANJING PT', 'KANDA, FUKUOKA',
       'YANGZHOU PT', 'TAURANGA', 'PORT WALCOTT', 'SENZAKI', 'TACOMA',
       'PORT SAID', 'KORSAKOV', 'KHOR AL FAKKAN', 'JAPAN ODAIBA',
       'KURE, HIROSHIMA', 'OURA/ARIAKE', 'NIIHAMA', 'YAMAGUCHI',
       'ONAHAMA', 'AN PING', 'TARAWA', 'SHIKAMA', 'FUNAFUTI', 'YANGSHAN',
       'LINGGA, SARAWAK', 'HUANGHUA', 'MATSUSHIMA, NAGASAKI',
       'PORT DALRYMPLE', 'KATAKAMI', 'CALLAO', '부평/인천', 'KASHIMA, SAGA',
       'PORTKELANG', 'PANJIN', 'SAKAISENBOKU', 'HINASE',
       'FUKUYAMA, KAGOSHIMA', 'SAIGO, SHIMANE', 'FREDERICKTOWN', 'HAMADA',
       'PICTON', 'DONGYING', 'KAWANOE', 'MATANE', 'NAOETSU', 'KINGSTON',
       'LAIZHOU', 'NADAHAMA', 'SAI GON PT', 'JINGJIANG PT', 'HUALIEN',
       'TOUYO', 'DAFENG PT', 'KOZMINO PORT', 'NAGOYA, OITA', 'FUZHOU PT',
       'HITACHI', 'YAWATA, FUKUOKA', 'SASEBO', 'NORO, NEW GEORGIA',
       'YIZHENG', 'ZHANGZHOU PT', 'CAPE TOWN', 'SAIPAN', 'CANAL',
       'HONGAI', 'ONOMICHI', 'GO DAU A TERMINAL', 'BOTANY BAY',
       'BINTULU, SARAWAK', 'BLUFF', 'DAS ISLAND', 'HUANGPU PT',
       'ANTOFAGASTA', 'CLATSKANIE', 'ABBOT POINT', 'PHITSANULOK',
       'NOSHIRO', 'ADANG BAY', 'VISAKHAPATNAM', 'DAYAOWAN',
       'CHANGZHOU, JIANGAU', 'HIRO', 'CORPUSCHRISTI', 'ALBANY, NY',
       'GALVESTON', 'KUMAMOTO', 'KAGOSHIMA', 'DAGANG', 'WOODRIVER',
       'PANAMA, CIUDAD DE', 'MAIZURU', 'KALTAG', 'DONGJIANGKOU', 'OREGON',
       'BATAAN, MARIVELES', 'LIRQUEN', 'PHU MY', 'BALOGO/BATANGAS',
       'JEBEL ALI', 'CAIRNS', 'PORT MORESBY', 'ONSLOW', 'LU-HUA SHAN',
       'NECOCHEA', 'INDONESIA /OTHER-POR', 'KRIBI', 'JIAXING',
       'PELABUHAN FUTONG', 'LA LIBERTAD', 'QUANZHOU PT', 'PORTMANATEE',
       'HOUSTON, TX', 'KOKURA', 'TAICANG PT', 'PONTA DA MADEIRA',
       'QINZHOU PT', 'NAKETY', 'ISHINOMAKI', 'PARADIP GARH',
       'ILIGAN, MINDANAO', 'TAKASAGO', 'TANJUNG PELEPAS', 'DAMPIER',
       'MISUMI, KUMAMOTO', 'PANJANG', 'DUTCHHARBOR', 'TAKUMA',
       'LAEM CHABANG', 'JINSHAN', 'MAGADAN', 'OTHERS', 'ICHIHARA', 'SUEZ',
       'BAOSHAN PT', 'KWINANA', 'SHIMABARA', 'BONTANG, KL', 'FUSHIKI',
       'LUWUK', 'KAJIKI', 'GEELONG', 'TAGONOURA', 'TOWNSVILLE',
       'OMAEZAKI', 'GISBORNE', 'TAWAU, SABAH',
       'SHEKOU (CODE CHANGE CN SHK))', 'PORO', 'GRESIK, JAVA',
       'USELESS LOOP', 'KOCHI', 'MATARANI', 'MACKAY', 'RAS AL KHAIR',
       'HULUDAO PT', 'PENGGARANG/TANJ.PENGILEH', 'TUAPSE',
       'GRAYSHARBORCITY', 'GUANGZHOU', 'NAKANOSEKI', 'POSO, SULAWESI',
       'DONG NAI', 'DAFENG', 'POINT LISAS', 'KOROR', 'TANGSHAN',
       'WESTPORT/PORT KLANG', 'SODEGAURA', 'XINHUI PT', 'FREMANTLE',
       'KWAJALEIN', 'NOUMEA', 'COCHIN', 'VIETNAM /OTHER-PORT/',
       'PORT ELIZABETH', 'PENGLAI PT', 'MIIKE, TOKYO', 'TIANJIN PT',
       'KERTEH TERMINAL', 'CULAO', 'HIMEJI', 'ITAGUAI', 'POSYET',
       'ANCHORAGE', 'DUNEDIN', 'SANDAKAN, SABAH', 'ICHIKAWA',
       'TAMASHAIMA', 'SAGANOSEKI', 'SONGXIA PT', 'FANGCHENG PT', 'RODMAN',
       'HAY POINT', 'CHENNAI (EX MADRAS)', 'SHIBUSHI', 'CALAPAN/BATANGAS',
       'AOMORI', 'GAMBA', 'MATSUURA, OITA', 'MINA ABD ALLAH', 'CAM PHA',
       'SUAO', 'PISCO', 'MISHIMA, KAWANOE', 'MINE', 'MUARA PANTAI',
       'KHANOM', 'GERALDTON', 'QIANWAN', 'HAIPHONG', 'TOBATA, FUKUOKA',
       'STEWART', 'HAIKOU', 'TACHIBANA', 'RONGCHENG', 'TAIZHOU PT',
       'MIHARA', 'CHITA', 'COOSBAY', 'LAZARO CARDENAS', 'TEOUDIE', 'OKI',
       'KISHIWADA', 'KUNAK, SABAH', 'WENZHOU PT', 'PORTHUENEME',
       'BANJARMASIN', 'JIAXING PT', 'ZHANJIANG PT',
       'AUSTRALIA /OTHER-POR', 'Bunati', 'SUNGAI RENGIT',
       'DONALDSONVILLE', 'KOH SICHANG', 'XIAOHUDAO', 'SATTAHIP',
       'BINTUNI', 'PORTLAND, IN', 'ZURKU ISLAND', 'NEVELSK', 'NELSON',
       'MIYAKO, IWATE', 'CHENGXI', 'NEDERLAND, CO', 'ONODA',
       'SANFRANCISCO', 'CALETA COLOSO', 'DUMAI, SUMATRA',
       'POHNPEI (EX PONAPE)', 'SENDAISHIOGAMA', 'BEARCREEK',
       'LUSHUN NEW PT', 'SEVERO-KURILSK', 'MARSDEN POINT',
       'BRUNSWICK, GA', 'NAMIKATA', 'SHINMOJI', 'ASTORIA',
       'KIMANIS, SABAH', 'NGHI SON', 'HUIZHOU PT', 'NEWORLEANS',
       'SIAM BANGKOK PORT', 'MIYAZU', 'TARJUN', 'LUANJIAKOU', 'MATSUNAGA',
       'LONGVIEW', 'MAZATLAN', 'KURE, KOCHI', 'CIGADING, JV', 'SHIGEI',
       'BATONROUGE', 'CHARLESTON, SC', 'CHAN MAY PORT', 'MAANSHAN PT',
       'CHINA/MACHONG', 'SAN NICOLAS', 'ISABEL', 'SUNRISEBEACH', 'SIKA',
       'RAYONG', 'SAIKI', 'XIUYU', 'TOKUSHIMA', 'NEW WESTMINSTER',
       'SAN ANTONIO', 'MAGADANSKY, PORT', 'AMAGASAKI', 'MAKURAZAKI',
       'SOVETSKAYA GAVAN', 'MORRO REDONDO', 'FERNDALE, WA', 'XIAMEN PT',
       'DALRYMPLE ISLET', 'MAOMING', 'MALACCA', 'HONIARA, GUADALCANAL IS',
       'KASADO', 'COLLEGEVILLE, MN', 'PLAQUEMINE', 'MUARA BERAU',
       'OFFSHORE FUJAIRAH', 'IWAGI,EHIME', 'TATSUGO', 'MERAK, JAVA',
       'DEVONPORT', 'BASUO', 'USUKI', 'CAI MEP INTERNATIONAL TERMINAL',
       'CAVITE, LUZON', 'WESTERNPORT', 'MEJILLONES',
       'MEXICO /OTHER-PORT/', 'COLOMBO', 'TADOTSU', 'CHENJIAGANG',
       'GUANGZHOU PT', 'NAGAHAMA, EHIME', 'BENICIA', 'MIN-AL-FAHAL',
       'BACON/LEGASPI', 'FREEPORT, TX', 'LAUTOKA', 'PRINCE RUPERT',
       'GULEI', 'ENSENADA', 'HIBI', 'BONNY', 'MIIKE, FUKUOKA',
       'PALEMBANG, SUMATRA', 'VINH', 'DALIAN PT', 'WUHU PT', 'OTHER PORT',
       'BANGKOK', 'EL ISKANDARIYA (ALEXANDRIA)', 'TAKAMATSU',
       'HIROTA, IWATE', 'MIYAZAKI, MIYAZAKI', 'SUVA', 'PORTANGELES',
       'TSUSHIMA, NAGASAKI', 'JUAYMAH TERMINAL', 'PASIR GUDANG, JOHOR',
       'MIRI, SARAWAK', 'TAHARA', 'AIOI', 'PANAMACITY', 'HIKARI',
       'KEMAMAN', 'RICHMOND, CA', 'KOTA KINABALU, SABAH', 'OLYMPIA',
       'NAKAGUSUKU', 'YOKOSUKA', 'HIDAKA', 'SUBIC BAY', 'PORT TEWFIK',
       'AD DAMMAM', 'FUQING', 'LAKECHARLES', 'TSURUMI, KANAGAWA',
       'HO CHI MINH, VICT', 'HIKOSHIMA', 'HIZENOHSHIMA', 'BURNIE',
       'GRAMERCY', 'MATSUURA, KAGOSHIMA', 'SERIA', 'HABU, HIROSHIMA',
       'SURABAYA', 'FUKUOKA, FUKUOKA', 'GEISMAR', 'CAPE FLATTERY',
       'WEIHAI PT', 'VUDA', 'BAN MAP TA PHUT', 'MALAYSIA /OTHER-PORT',
       'VALDEZ', 'DANDONG', 'HUMEN PT', 'GENERAL SANTOS', 'NUMAZU',
       'NIPAH', 'PITTSBURG, CA', 'KASHIWAZAKI', 'ASHBURTON', 'GUAM',
       'QUI NHON', 'JURONG', 'YANGPU PT', 'SALVADOR', 'KITANADA',
       'NIIGATAHIGASHI', 'FUKUI', 'NEW MANGALORE',
       'CAGAYAN DE ORO, MINDANAO', 'SHARK BAY', 'PUTIAN', 'CEBU',
       'QUANZHOU', 'SHANTOU PT', 'BOGO/CAGAYAN DE ORO', 'CAMRANH',
       'CO-OPERATION ZONE A (AU,ID)', 'SALDANHA BAY', 'MAMONAL',
       'WESTHAMPTONBEACH', 'BERGEN', 'TAKAHAMA/AMAKUSA', 'ZHUHAI PT',
       'JAMBI, SUMATRA', 'EBEYE', 'NEPOUI', 'SHENZHEN',
       'NANYO, YAMAGUCHI', 'KIMBE', 'SHIMOJISHIMA, OKINAWA',
       'TANJUNG LANGSAT', 'ACAJUTLA', 'SATUI', 'SANBAIMEN',
       'ECUADOR /OTHER-PORT/', 'BARROW ISLAND, WA', 'TONDA',
       'TONGLING PT', 'HIAGARI/KITAKIUSHU', 'PORTO ALEGRE', 'TUTICORIN',
       'BING BONG', 'SALALAH', 'ONISHI', 'PORT KEMBLA', 'NANAIMO',
       'Calaca', 'NEDERLAND, TX', 'DEFENG', 'TANIYAMA', 'JUBAIL',
       'HOUSTON, PA', 'PORT MOODY', 'PUERTO QUETZAL', 'GOVE',
       'LEGASPI APT, LUZON', 'ALBANY', 'BANGGAI', 'CAPE CUVIER', 'JOETSU',
       'NAPIER', 'HAIYANG', 'PUNTA LOBITOS', 'KUMAI', 'SAKURAJIMA',
       'HIROHATA', 'KUALA ENOK', 'HIRARA', 'PHILADELPHIA', 'YUSU',
       'OTHER', 'MAKASSAR', 'USHIBUKA', 'PONTIANAK, KALIMANTAN',
       'VICTORIA', 'PAMPLONA/APARRI', 'HAKATASHIMA',
       'PIPAVAV (VICTOR) PORT', 'FUTAJIMA, FUKUOKA', 'WENZHOU',
       'FUKUSHIMA, MIYAZAKI', 'CONSTANTA', 'UMM QASR', 'CILEGON',
       'PHILIPPINES /OTHER-P', 'DUNG QUAT', 'MASCOT', 'SANTOS',
       'JASAAN/CAGAYAN DE ORO', 'HAIMEN', 'HUASCO', 'NAGASU, KUMAMOTO',
       'OHGISHIMA', 'LUOYANG', 'GO DAU B TERMINAL', 'YAWATAHAMA',
       'MOURILYAN', 'BUNBURY', 'WELLINGTON', 'ELLISVILLE, MS', 'MARSHALL',
       'KANDLA', 'KOSRAE (EX KUSAIE)', 'ZHENHAI PT', 'SRIRACHA',
       'ROSARITO TERMINAL', 'BENOA, BALI', 'CAP LOPEZ', 'YANGJIANG PT',
       'NOBEOKA', 'SYDNEY', 'ALBUERA', 'COLON', 'MINAMATA', 'TSUNEISHI',
       'JINGZHOU PT', 'SUNGAI PAKNING, SUMATRA', 'ISHIGAKI', 'IQUIQUE',
       'OHIGAWA', 'NANKO', 'ANGRA DOS REIS', 'PORT CHALMERS', 'CHONGMING',
       'AUCKLAND', 'BACOLOD, NEGROS', 'KUWAIT', 'HUANGPU NEW PORT',
       'BRASS', 'TANJONG BIN', 'KYOTO, KYOTO', 'VIZAGAPATANAM',
       'COLUMBUS, MO', 'TANGSHAN PT', 'KOUAOUA', 'RABAUL', 'MUARA',
       'EGYPT /OTHER-PORT/', 'XINSHA', 'ONOMICHIITOZAKI', 'KINOE',
       'KAVKAZ', 'MELBOURNE', 'MAJI SHAN', 'SANTO DOMINGO',
       'KINNAKAGUSUKU', 'GUAYMAS', 'MUMBAI (EX BOMBAY)', 'CUA VIET PORT',
       'TANJUNG PRIOK', 'NEWPORT, OR', 'HALDIA', 'NAKATSU', 'TAMANO',
       'KHOR AL ZUBAIR', 'MITSUKOSHIMA', 'YAMAGAWA',
       'KAWAJIRI, HIROSHIMA', 'TENERIFE', 'TAIWAN PRO.OF CHINA',
       'TAGOLOAN MIS.', 'BENGKULU, SUMATRA', 'LA PAZ',
       'LUGAIT/CAGAYAN DE ORO', 'KONE', 'SOYO', 'DUQM', 'OTARU',
       'PEARLHARBOR', 'CEYHAN', 'THA SALA', 'LYTTELTON', 'CIENAGA',
       'PUNTA MORALES', 'IWANAI', 'BROOME', 'GAMAGORI', 'COLON FREE ZONE',
       'HAMBANTOTA', 'BATAM ISLAND', 'AKITSU', 'SAIJO', 'OBI ISLAND',
       'NETHERLANDS ANTILLES', 'YAP', 'BENETE', 'JEDDAH', 'NAURU ISLAND',
       'SOHAR', 'ZHONGSHAN PT', 'MACUN', 'KANOKAWA', 'SAN JOSE',
       'PORT ALMA', 'DAMMAN', 'LOBITOS', 'CORINTO', 'YANGKOU', 'KISARAZU',
       'PORT VILA', 'MALABO', 'MAB TAPUD', 'TABANGOA', 'SANTA MARTA',
       'SHENHU', 'KITIMAT', 'CHERRYPOINT', 'MADANG', 'HOUND POINT',
       'JIEYANG', 'OROBAY', 'KASAOKA', 'KOLKATA (EX CALCUTTA)', 'HANNAN',
       'INNOSHIMA', 'PUERTO COLOMBIA', 'KITAKYUSHU', 'LONG YAN'],
      dtype=object)

In [19]:
China_port = ['XIAMEN','TAICANG','NINGBO','SHANGHAI','QINGDAO PT','CAOJING','BAYUQUAN','CHANGSHU','ZHENJIANG PT',
              'LIANYUNGANG','ZHANGJIAGANG','ZHAPU','QINGDAO','DANDONG PT','SHIDAO PT','YANTAI','YANTIAN PT',
              'TIANJIN','JINGTANG(TANGSHAN)','DALIAN','ZHOUSHAN PT','NANTONG PT','QINHUANGDAO PT','TAIXING','NANJING',
              'WEIHAI','JINZHOU PT','WAIGAOQIAO PT','LONGKOU PT','CHANGSHU PT','JIANGYIN PT','HUANGHUA PT','RUGAO PT',
              'CAOFEIDIAN PT','LANSHAN PT','ZHAPU PT','DONGYING PT','RIZHAO PT','TIANJIN XINGANG PT','BEIHAI PT','WEIFANG PT',
              'ZHANJIANG','SHEKOU PT','SHANTOU','NINGDE','DONGGUAN PT','NANSHA PT','LONGYAN PT','LAIZHOU PT','TAIZHOU',
              'YANTAI PT','WEIFANG','JINGJIANG','FUJIN','JIUZHOU PT','NINGBO PT','YINGKOU PT','JIANGYIN','SHANGHAI PT',
              'CHANGZHOU PT','JINGTANG PT','DA CHAN BAY','FUZHOU','Qidong Pt','XINGANG','PENGLAI','NANJING PT',
              'YANGZHOU PT','YANGSHAN','HUANGHUA','PANJIN','DONGYING','LAIZHOU','JINGJIANG PT','DAFENG PT','FUZHOU PT',
              'YIZHENG','ZHANGZHOU PT','HUANGPU PT','DAYAOWAN','CHANGZHOU, JIANGAU','DAGANG','DONGJIANGKOU','LU-HUA SHAN',
              'JIAXING','QUANZHOU PT','TAICANG PT','QINZHOU PT','JINSHAN','BAOSHAN PT','SHEKOU (CODE CHANGE CN SHK))',
              'HULUDAO PT','GUANGZHOU','DAFENG','TANGSHAN','XINHUI PT','PENGLAI PT','TIANJIN PT','SONGXIA PT','FANGCHENG PT',
              'QIANWAN','HAIKOU','RONGCHENG','TAIZHOU PT','WENZHOU PT','JIAXING PT','ZHANJIANG PT','XIAOHUDAO','CHENGXI',
              'LUSHUN NEW PT','HUIZHOU PT','LUANJIAKOU','MAANSHAN PT','CHINA/MACHONG','XIUYU','XIAMEN PT','MAOMING','BASUO',
              'CHENJIAGANG','GUANGZHOU PT','GULEI','DALIAN PT','WUHU PT','FUQING','WEIHAI PT','DANDONG','HUMEN PT','YANGPU PT',
              'PUTIAN','QUANZHOU','SHANTOU PT','ZHUHAI PT','SHENZHEN','SANBAIMEN','TONGLING PT','DEFENG','HAIYANG','WENZHOU',
              'HAIMEN','LUOYANG','ZHENHAI PT','YANGJIANG PT','JINGZHOU PT','CHONGMING','HUANGPU NEW PORT','TANGSHAN PT',
              'XINSHA','MAJI SHAN' ]

Asia_port = ['NEGHISHI/YOKOHAMA','SHIMONOSEKI','KOBE','OITA','FUKUYAMA, HIROSHIMA','NANAO',
             'AKITA','IMABARI','HAKATA/FUKUOKA','TOYAMA','MIZUSHIMA','KIKUMA','SENDAI, MIYAGI',
             'NIIGATA','YOKOHAMA','OSAKA','IYOMISHIMA','WAKAMATSU/KITAKYUSHU','TSUKUMI','SAKAI',
             'MOJI/KITAKYUSHU','TOYOHASHI','HIROSHIMA','TOKUYAMA','HIBIKINADA, FUKUOKA','SAKAIDE',
             'WAKAYAMA','KUSHIRO','IZUHARA','HITAKATSU','YOKKAICHI','NAOSHIMA','SHIMOTSU',
             'HIGASHIHARIMA','KINUURA','ISHIKARIWAN-SHINKO, HOKKAIDO','SHIMIZU','CHOFU','FUNABASHI',
             'RUMOI','MATSUYAMA','MURORAN','NAGASAKI','TSURUGA','NAGOYA, AICHI','TOMAKOMAI',
             'KAKOGAWA','KUROSAKI','HITACHINAKA','KUDAMATSU','HIGASHI-OGISHIMA','HACHINOHE',
             'KANAZAWA','TOKYO','MISUMI, SHIMANE','IMARI','IWAKUNI','UBE','KASHIMAE','MITAJIRI',
             'KAWASAKI','SAKATA','OKINAWA, OKINAWA','HOSOSHIMA','ITOZAKI','SAKAIMINATO','OTAKE'
             'UWAJIMA','YATSUSHIRO','SUSAKI','SATSUMASENDAI','KIIRE','KOMENOTSU','ETAJIMA','ARIAKE, TOKYO',
             'KASHIMA, IBARAKI','ISHIKARI','KIMITSU','NAHA, OKINAWA','HAKODATE','WAKAMATSU, NAGASAKI',
             'HIMEKAWA','MUTSURE','OSHIMA, NAGASAKI','REIHOKU','MATSUURA, NAGASAKI','TOYAMASHINKO',
             'SENZAKI','JAPAN ODAIBA','KURE, HIROSHIMA','OURA/ARIAKE','NIIHAMA','YAMAGUCHI','ONAHAMA',
             'SHIKAMA','MATSUSHIMA, NAGASAKI','KATAKAMI','KASHIMA, SAGA','SAKAISENBOKU','HINASE',
             'FUKUYAMA, KAGOSHIMA','SAIGO, SHIMANE','HAMADA','KAWANOE','NAOETSU','NADAHAMA',
             'TOUYO','NAGOYA, OITA','HITACHI','YAWATA, FUKUOKA','SASEBO','ONOMICHI','NOSHIRO',
             'HIRO','KUMAMOTO','KAGOSHIMA','MAIZURU','ISHINOMAKI','KOKURA','TAKASAGO','MISUMI', 
             'KUMAMOTO','TAKUMA','ICHIHARA','SHIMABARA','FUSHIKI','KAJIKI','TAGONOURA','OMAEZAKI'
             'NAKANOSEKI','SODEGAURA','MIIKE, TOKYO','HIMEJI','ICHIKAWA','TAMASHAIMA','SAGANOSEKI',
             'SHIBUSHI','AOMORI','MISHIMA, KAWANOE','TOBATA, FUKUOKA','TACHIBANA','MIHARA','CHITA',
             'OKI','KISHIWADA','MIYAKO, IWATE','ONODA','SENDAISHIOGAMA','NAMIKATA','SHINMOJI','MIYAZU',
             'MATSUNAGA','KURE, KOCHI','SHIGEI','SAIKI','TOKUSHIMA','AMAGASAKI','MAKURAZAKI','KASADO',
             'IWAGI,EHIME','TATSUGO','USUKI','TADOTSU','NAGAHAMA, EHIME','MIIKE, FUKUOKA','TAKAMATSU',
             'HIROTA, IWATE','MIYAZAKI, MIYAZAKI','TSUSHIMA, NAGASAKI','TAHARA','AIOI','HIKARI','NAKAGUSUKU',
             'YOKOSUKA','HIDAKA','TSURUMI, KANAGAWA','HIKOSHIMA','HIZENOHSHIMA','MATSUURA, KAGOSHIMA',
             'HABU, HIROSHIMA','FUKUOKA, FUKUOKA','NUMAZU','KASHIWAZAKI','KITANADA','NIIGATAHIGASHI',
             'KANDA, FUKUOKA','TAKAHAMA/AMAKUSA','NANYO, YAMAGUCH','SHIMOJISHIMA, OKINAWA',
             'HIAGARI/KITAKIUSHU','ONISHI','TANIYAMA','JOETSU','SAKURAJIMA','HIROHATA','HIRARA','YUSU',
             'USHIBUKA','HAKATASHIMA','FUTAJIMA, FUKUOKA','FUKUSHIMA, MIYAZAKI','NAGASU, KUMAMOTO',
             'OHGISHIMA','YAWATAHAMA','NOBEOKA','MINAMATA','TSUNEISHI','ISHIGAKI','OHIGAWA','NANKO',
             'KYOTO, KYOTO','ONOMICHIITOZAKI','KINOE','KINNAKAGUSUKU',
             'MAI-LIAO','AN PING','SUAO','KAOHSIUNG','TAIPEI','TAICHUNG','KAINAN','KEELUNG (CHILUNG)','HUALIEN',
             'SON DUONG','VUNG TAU','PHUOC LONG','CAI LAN','HO CHI MINH CITY','VAN PHONG','DA NANG'
             'SAI GON PT','HONGAI','GO DAU A TERMINAL','PHU MY','DONG NAI','CAM PHA','HAIPHONG','NGHI SON',
             'CHAN MAY PORT','CAI MEP INTERNATIONAL TERMINAL','VINH','HO CHI MINH, VICT','QUI NHON','FUKUI',
             'CAMRANH','DUNG QUAT','GO DAU B TERMINAL','HONG KONG','VICTORIA',
             'TARAKAN, KALIMANTAN','TANJUNG BARA, KL','BITUNG, SULAWESI','ANYER KIDUL','SAMARINDA, KALIMANTAN',
             'BALIKPAPAN','AMAMAPARE, IJ','PADANG','TABONEO','JAKARTA, JAVA','ADANG BAY','PELABUHAN FUTONG',
             'PANJANG','BONTANG, KL','LUWUK','GRESIK, JAVA','PENGGARANG/TANJ.PENGILEH','POSO, SULAWESI','MUARA PANTAI',
             'BANJARMASIN','Bunati','BINTUNI','DUMAI, SUMATRA','TARJUN','CIGADING, JV','MUARA BERAU','MERAK, JAVA',
             'PALEMBANG, SUMATRA','SURABAYA',"JAMBI, SUMATRA",'SATUI','TONDA','BANGGAI','KUMAI','KUALA ENOK',
             'PONTIANAK, KALIMANTAN','CILEGON','BENOA, BALI','SUNGAI PAKNING, SUMATRA','TANJONG BIN',
             'DAVAO, MINDANAO','BATANGAS/LUZON','ROXAS/PUERTO PRINCESA','LIMAY/BATAAN','MANILA SOUTH HARBOUR'
             'MANILA','BATAAN, MARIVELES','BALOGO/BATANGAS','ILIGAN, MINDANAO','PORO','CULAO','CALAPAN/BATANGAS'
             'ALBUERA','PAMPLONA/APARRI','CAVITE, LUZON','BACON/LEGASPI','HIBI','SUBIC BAY','GENERAL SANTOS',
             'CAGAYAN DE ORO, MINDANAO','CEBU','BOGO/CAGAYAN DE ORO','Calaca','LEGASPI APT, LUZON','JASAAN/CAGAYAN DE ORO',
             'BACOLOD, NEGROS','BASRA','UMM QASR','GALLE','COLOMBO','RAS TANURA',
             'YANBU AL-BAHR','RAS AL KHAIR', 'JUAYMAH TERMINAL','AD DAMMAM','JUBAIL',
             'QALHAT','MIN-AL-FAHAL','SALALAH',	'SINGAPORE','JURONG','AL FUJAYRAH','RUWAIS','KHOR AL FAKKAN',
             'DAS ISLAND','JEBEL ALI','ZURKU ISLAND','OFFSHORE FUJAIRAH','RAS LAFFAN','LAHAD DATU, SABAH',
             'LUMUT','LABUAN, SABAH','LINGGA, SARAWAK','PORTKELANG','BINTULU, SARAWAK','TANJUNG PELEPAS',
             'TAWAU, SABAH','WESTPORT/PORT KLANG','KERTEH TERMINAL','SANDAKAN, SABAH','KUNAK, SABAH',
             'SUNGAI RENGIT','KIMANIS, SABAH','MALACCA','PASIR GUDANG, JOHOR',"MIRI, SARAWAK",'KEMAMAN',
             'KOTA KINABALU, SABAH','SERIA','TANJUNG LANGSAT','MAKASSAR','MINA AL AHMADI','MINA ABD ALLAH',
             'KUWAIT','SITRAH','PHITSANULOK','LAEM CHABANG','KHANOM','KOH SICHANG','SATTAHIP','SIAM BANGKOK PORT','RAYONG',
             'BANGKOK','BAN MAP TA PHUT','SHARK BAY','SRIRACHA','PARADIP GARH','VISAKHAPATNAM','KOCHI',
             'COCHIN','CHENNAI (EX MADRAS)','SIKA','NIPAH','NEW MANGALORE','TUTICORIN','PIPAVAV (VICTOR) PORT',
             'KANDLA','VIZAGAPATANAM','MUMBAI (EX BOMBAY)','MUARA']

Oceania_port=['KOROR','POHNPEI (EX PONAPE)','LAUTOKA','SUVA','VUDA','PORT MORESBY','RABAUL','NAKETY','NOUMEA','TEOUDIE',
              'NEPOUI','KOUAOUA','TARAWA','FUNAFUTI','NORO, NEW GEORGIA','HONIARA, GUADALCANAL IS','TIMARU','TAURANGA',
              'PICTON','BLUFF','DUNEDIN','NEDERLAND, CO','MARSDEN POINT','ASHBURTON','NAPIER','WELLINGTON','PORT CHALMERS',
              'AUCKLAND','BRISBANE','GLADSTONE','DARWIN','PORT HEDLAND','BARROW ISLAND','GROOTE EYLANDT','WYNDHAM',
              'PORT WALCOTT','BOTANY BAY','ABBOT POINT','CAIRNS','ONSLOW','DAMPIER','KWINANA','GEELONG','GISBORNE',
              'USELESS LOOP','MACKAY','FREMANTLE','HAY POINT','MATSUURA, OITA','GERALDTON','NELSON',
              'ISABEL','SUNRISEBEACH','DALRYMPLE ISLET','ALBANY','DEVONPORT','WESTERNPORT','CAPE FLATTERY','BURNIE',
              'PORT DALRYMPLE','KIMBE','BARROW ISLAND, WA','BING BONG','PORT KEMBLA','GOVE','CAPE CUVIER',
              'MASCOT','MOURILYAN','BUNBURY','SYDNEY','MELBOURNE','NEWCASTLE','MAJURO','KWAJALEIN','EBEYE','MARSHALL']

Europe_port = ['PAPEETE','BERGEN','CONSTANTA',
               'NOVOROSSIYSK', 'VLADIVOSTOK', 'NAKHODKA', "BUKHTA OL'GA", 'PETROPAVLOVSK-KAMCHATSKIY','KHOLMSK',
               'VOSTOCHNYY PORT','ZARUBINO','VANINO','SLAVYANKA','DE-KASTRI','PRIGORODNOYE',"YUZHNO-KURIL'SK",'PLASTUN',
               'OKHOTSK','KORSAKOV','KOZMINO PORT','MAGADAN','TUAPSE','POSYET','SEVERO-KURILSK','MAGADANSKY, PORT',
               'SOVETSKAYA GAVAN','KAVKAZ','SHAKHTERSK' ]

America_port = ['OCEAN DISTRICT','BALBOA','SEATTLE','BEAUMONT, TX','ROBERTS BANK','CRISTOBAL','VANCOUVER','OAKLAND, CA',
                'LONGBEACH','PORTLAND, OR','SANDIEGO','HONOLULU','CAYO ARCAS TERMINAL','MANZANILLO','PORT MELLON','BAHIA BLANCA',
                'NORTH PACIFIC OCEAN','TROIS-RIVIERES (THREE RIVERS)','LOSANGELES','TACOMA',
                'CALLAO','FREDERICKTOWN','MATANE','CANAL','ANTOFAGASTA','CLATSKANIE','CORPUSCHRISTI','ALBANY, NY','GALVESTON',
                'WOODRIVER','PANAMA, CIUDAD DE','KALTAG','OREGON','LIRQUEN','NECOCHEA','LA LIBERTAD','PORTMANATEE','HOUSTON, TX',
                'PONTA DA MADEIRA','TOWNSVILLE','MATARANI','GRAYSHARBORCITY','POINT LISAS','ITAGUAI','ANCHORAGE','RODMAN','PISCO',
                'MINE','STEWART','COOSBAY','LAZARO CARDENAS','PORTHUENEME','DONALDSONVILLE','PORTLAND, IN','SANFRANCISCO',
                'CALETA COLOSO','BEARCREEK','BRUNSWICK, GA','ASTORIA','NEWORLEANS','LONGVIEW','MAZATLAN','BATONROUGE',
                'CHARLESTON, SC','SAN NICOLAS','NEW WESTMINSTER','SAN ANTONIO','MORRO REDONDO','FERNDALE, WA','COLLEGEVILLE, MN',
                'PLAQUEMINE','MEJILLONES','MEXICO /OTHER-PORT/','BENICIA','FREEPORT, TX','PRINCE RUPERT','ENSENADA','PORTANGELES',
                'PANAMACITY','RICHMOND, CA','OLYMPIA','LAKECHARLES','GRAMERCY','GEISMAR','VALDEZ','PITTSBURG, CA',
                'GUAM','SALVADOR','MAMONAL','WESTHAMPTONBEACH','ACAJUTLA','ECUADOR /OTHER-PORT/','PORTO ALEGRE','NANAIMO',
                'NEDERLAND, TX','HOUSTON, PA','PORT MOODY','PUERTO QUETZAL','ALBANY','PUNTA LOBITOS','PHILADELPHIA',
                'SANTOS','HUASCO','ELLISVILLE, MS','ROSARITO TERMINAL','COLON','IQUIQUE',
                'ANGRA DOS REIS','COLUMBUS, MO','SANTO DOMINGO','GUAYMAS', 'SABINE','KINGSTON' ,'DUTCHHARBOR','SAIPAN']

Africa_port = ['RICHARDS BAY','PORT LOUIS','EL SUWEIS' , 'PORT SAID','CAPE TOWN','KRIBI','SUEZ','PORT ELIZABETH',
               'GAMBA','BONNY','EL ISKANDARIYA (ALEXANDRIA)','PORT TEWFIK','SALDANHA BAY','CAP LOPEZ','BRASS','EGYPT /OTHER-PORT/']

In [20]:
def code( x ) : 
    if x in China_port :
        return "China"
    
    elif x in Asia_port :
        return "Asia"
    
    elif x in America_port :
        return "America"
    
    elif x in Africa_port :
        return "Africa"
    
    elif x in Europe_port :
        return "Europe"
    
    elif x in Oceania_port :
        return "Oceania"
    
    else :
        return "etc"

In [21]:
df['Ship_Prev_port'] = df['Ship_Prev_port'].apply( lambda x : code( x ) )

In [22]:
df.drop( [ 'Ship_departure', 'Ship_Nation', 'Ship_purpose'], axis=True, inplace=True)

In [23]:
df['Ship_arrival'] = df['Ship_arrival'].apply( lambda x : x[:10])

In [24]:
df['Ship_arrival'] = df['Ship_arrival'].apply( lambda x : int(x.replace('-', '')))

In [25]:
df.rename(columns={"Ship_arrival":"Date"},inplace=True)

In [26]:
df.head()

,Ship_year,Ship_count,Ship_Total_tonnage,Date,Ship_Prev_port,Ship_crew(korea),Ship_crew(foreign),Ship_passenger
41147,2020,1,749,20200428,etc,3.0,5.0,0.0
42978,2019,9,"17,225",20191201,China,0.0,20.0,0.0
42979,2019,3,"4,060",20191201,Asia,5.0,12.0,0.0
42980,2019,130,465,20191201,Asia,4.0,7.0,0.0
42982,2019,44,"5,534",20191201,Asia,5.0,10.0,0.0

In [27]:
china_df = df[ df['Ship_Prev_port'] == 'China' ]
asia_df = df[ df['Ship_Prev_port'] == 'Asia' ]
america_df = df[ df['Ship_Prev_port'] == 'America' ]
africa_df = df[ df['Ship_Prev_port'] == 'Africa' ]
europe_df = df[ df['Ship_Prev_port'] == 'Europe' ]
oceania_df = df[ df['Ship_Prev_port'] == 'Oceania' ]

In [28]:
china_group_df = china_df.groupby(china_df['Date']).sum()
asia_group_df = asia_df.groupby(asia_df['Date']).sum()
america_group_df = america_df.groupby(america_df['Date']).sum()
africa_group_df = africa_df.groupby(africa_df['Date']).sum()
europe_group_df = europe_df.groupby(europe_df['Date']).sum()
oceania_group_df = oceania_df.groupby(europe_df['Date']).sum()

In [29]:
china_group_df.head()

,Ship_year,Ship_count,Ship_crew(korea),Ship_crew(foreign),Ship_passenger
Date,,,,,
20191201,258432,1488,286.0,2254.0,1206.0
20191202,278622,3624,316.0,2786.0,5700.0
20191203,335154,3824,374.0,3134.0,5424.0
20191204,278622,3458,228.0,2720.0,5916.0
20191205,270546,3706,334.0,2586.0,5672.0

In [30]:
china_group_df.to_csv('../data/Ship/China_group_df.csv')
asia_group_df.to_csv('../data/Ship/Asia_group_df.csv')
america_group_df.to_csv('../data/Ship/America_group_df.csv')
africa_group_df.to_csv('../data/Ship/Africa_group_df.csv')
europe_group_df.to_csv('../data/Ship/Europe_group_df.csv')
oceania_group_df.to_csv('../data/Ship/Oceania_group_df.csv')